apiVersion: apps/v1
kind: Deployment
metadata:
  name: recomendador
  labels:
    app.kubernetes.io/name: recomendador
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: recomendador
      app.kubernetes.io/component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: recomendador
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: recomendador
          image: jorgerap1997/sistema_recomendador:latest
          command: ["/bin/sh", "-c", "sleep 40 && python app.py"]
          args:
            - --bind_ip
            - 0.0.0.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 4000
