apiVersion: v1
kind: Service
metadata:
  name: recomendador
  labels:
    app.kubernetes.io/name: recomendador
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app.kubernetes.io/name: recomendador
    app.kubernetes.io/component: backend